# Generated by Django 6.0 on 2025-12-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
