# Generated by Django 6.0 on 2025-12-27 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_taskupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='company.task'),
        ),
    ]
